version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image:
      app-python-flask
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:kevinpaz@db:5432/gestion_de_tareas
    volumes:
      - .:/app_2
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kevinpaz
      POSTGRES_DB: gestion_de_tareas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
